#!/usr/bin/env bash
# Re-generate the provisioning data from the machine this runs on.
# Run it on your working Kali box, then commit the result.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ART="$REPO/artifacts"
mkdir -p "$ART"

say() { printf '\n\033[1;34m==>\033[0m %s\n' "$1"; }

# ---------------------------------------------------------------- apt packages
say "Snapshotting apt packages"
# Non-default set: manually-installed packages minus the fresh Kali baseline
# shipped alongside this role. Regenerate the baseline on a fresh Kali with:
#   apt list --installed 2>/dev/null | cut -d/ -f1 | sort -u > \
#     roles/base_packages/files/kali-default-packages.txt
#
# REQUIRED_EXTRA: packages other roles' tasks depend on that a plain regen
# from apt-mark showmanual would otherwise drop.
#   - libjpeg-dev: volatility3's venv needs it to build Pillow from source.
#   - azure-cli: real supported path for az, via the microsoft-prod repo.
#   - gh: apt_repos configures the github-cli repo, but nothing lists gh itself.
#   - libldap2-dev, libsasl2-dev: python-ldap headers (windapsearch's
#     requirements.txt, shared venv).
REQUIRED_EXTRA=(libjpeg-dev azure-cli gh libldap2-dev libsasl2-dev)
apt-mark showmanual | sort > /tmp/.snap_manual
sort -u "$REPO/roles/base_packages/files/kali-default-packages.txt" > /tmp/.snap_base
{
  echo "---"
  echo "# Non-default apt packages: what this box has that a fresh Kali does not."
  echo "# apt-mark showmanual minus roles/base_packages/files/kali-default-packages.txt,"
  echo "# minus kernels and a small drop-list, plus REQUIRED_EXTRA below."
  echo "# Generated on $(date -I)."
  echo "# ad1tools is a local .deb (artifacts_sync); packages-microsoft-prod conflicts"
  echo "# with the microsoft repo apt_repos configures; tlauncher is non-pentest;"
  echo "# wine/wine32:i386/libwine/libwine:i386 unused and i386 multiarch was never"
  echo "# enabled anywhere, so the :i386 variants could never install anyway."
  echo "apt_packages:"
  { comm -23 /tmp/.snap_manual /tmp/.snap_base \
      | grep -vxE 'ad1tools|tlauncher-linux-installer|packages-microsoft-prod|wine|wine32:i386|libwine|libwine:i386' \
      | grep -vE '^(linux-image|linux-modules|linux-base|linux-binary)'
    printf '%s\n' "${REQUIRED_EXTRA[@]}"
  } | sort -u | sed 's/^/  - /'
} > "$REPO/roles/base_packages/vars/main.yml"

# ----------------------------------------------------------------------- pipx
say "Snapshotting pipx applications"
{
  echo "---"
  echo "# Auto-generated by scripts/snapshot.sh on $(date -I)"
  echo "pipx_packages:"
  pipx list --short | awk '{printf "  - { name: \"%s\", seen_version: \"%s\" }\n", $1, $2}'
} > "$REPO/roles/python_tools/vars/main.yml"

# ------------------------------------------------------------------ git repos
say "Snapshotting git tool repositories"
{
  echo "---"
  echo "# Auto-generated by scripts/snapshot.sh on $(date -I) -- always tracks upstream HEAD."
  echo 'git_tools_dir: "{{ ansible_env.HOME }}/tools"'
  echo "git_tools:"
  for d in "$HOME"/tools/*/; do
    u=$(git -C "$d" remote get-url origin 2>/dev/null) || continue
    printf '  - { name: "%s", repo: "%s" }\n' "$(basename "$d")" "$u"
  done
  echo ""
  echo "# Repos that live outside ~/tools"
  echo "git_tools_extra:"
  for d in "$HOME"/Downloads/*/ "$HOME"/Downloads/windows/*/; do
    u=$(git -C "$d" remote get-url origin 2>/dev/null) || continue
    rel="${d#"$HOME"/}"; rel="${rel%/}"
    printf '  - { name: "%s", repo: "%s", dest: "{{ ansible_env.HOME }}/%s" }\n' \
      "$(basename "$d")" "$u" "$rel"
  done
} > "$REPO/roles/git_tools/vars/main.yml"

# ------------------------------------------------------------------- payloads
say "Building payload archives (this takes a minute)"

# Directories under Downloads that are git clones -- provisioned by git_tools,
# excluded from the tarball so the payload stays small and stays current.
GIT_EXCLUDES=()
for d in "$HOME"/Downloads/*/ "$HOME"/Downloads/windows/*/; do
  git -C "$d" rev-parse --git-dir >/dev/null 2>&1 || continue
  rel="${d#"$HOME"/}"
  GIT_EXCLUDES+=( --exclude="${rel%/}" )   # trailing slash would not match
done

tar -C "$HOME" --zstd -cf "$ART/downloads.tar.zst" \
  --exclude='Downloads/cacert.der' \
  "${GIT_EXCLUDES[@]}" \
  Downloads

tar -C "$HOME" --zstd -cf "$ART/C.tar.zst" C

tar -C "$HOME/tools" --zstd -cf "$ART/local-debs.tar.zst" \
  ad1tools_1.0.0-1_amd64.deb

# Custom binaries in /usr/bin and /usr/local/bin not owned by any apt package.
# Rooted at / so paths and executable bits restore verbatim.
tar -C / --zstd -cf "$ART/system-bins.tar.zst" \
  usr/bin/gdre_tools.x86_64 \
  usr/bin/gdre_tools.pck \
  usr/bin/libGodotMonoDecompNativeAOT.so \
  usr/bin/pycdc \
  usr/bin/utmdump \
  usr/local/bin/kerbrute

say "Done. Archive sizes:"
du -sh "$ART"/*.tar.zst
say "Review 'git status', then commit."
